# Generated by Django 6.0.6 on 2026-06-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('experience', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
